image: ghcr.io/cirruslabs/flutter:beta

stages: [build]

cache:
  key: $CI_JOB_NAME
  paths:
    - .pub-cache
    - build

# --------------------------------------------------------------------------------
build_android:
  image: ghcr.io/cirruslabs/flutter:beta-android   # уже содержит SDK
  stage: build
  script:
    - flutter pub get
    - flutter build apk --release --dart-define=ENV=production
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
    expire_in: 1 week

# --------------------------------------------------------------------------------
build_linux:
  stage: build
  before_script:
    # Cirrus image уже имеет GTK и CMake; добавляем dev-libs для plugins
    - apt-get update && apt-get install -y libjsoncpp-dev libsecret-1-dev
  script:
    - flutter pub get
    - flutter build linux --release --dart-define=ENV=production
  artifacts:
    paths:
      - build/linux/**/release/bundle
    expire_in: 1 week