# NeoMovies – GitLab CI (shared runners only)
# Builds release APK (Android) and Linux desktop bundle using GitLab.com shared Docker runners.

image: cirrusci/flutter:3.22

stages:
  - build

variables:
  PUB_CACHE: "$CI_PROJECT_DIR/.pub-cache"

cache:
  key: $CI_JOB_NAME
  paths:
    - .pub-cache
    - build

before_script:
  - flutter --version
  - flutter pub get

build_android:
  stage: build
  script:
    - flutter build apk --release --dart-define=ENV=production
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
    expire_in: 1 week

build_linux:
  stage: build
  # Need extra system packages for GTK etc.
  script:
    - apt-get update && apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
    - flutter config --enable-linux-desktop
    - flutter build linux --release --dart-define=ENV=production
  artifacts:
    paths:
      - build/linux/**/release/bundle
    expire_in: 1 week